#!/bin/bash

set -euo pipefail

OUTPUT_CSV="pokemon_report.csv"
echo "Name,Height (m),Weight (kg)" > "$OUTPUT_CSV"

jq -r '. | [.name, .height/10, .weight/10] | @csv' pokemon_data/*.json >> "$OUTPUT_CSV"


awk -F',' '
  NR > 1 {
    total_height += $2;
    total_weight += $3;
  }
  END {
    num_records = NR - 1;
    if (num_records > 0) {
      print "\nAverage Height: " total_height / num_records " m";
      print "Average Weight: " total_weight / num_records " kg";
    }
  }
' "$OUTPUT_CSV"

echo "CSV Report generated at: $OUTPUT_CSV"
